# SwiftBar build & release automation.
#
# The release flow encodes hard-won constraints:
# - Build with a RELEASED Xcode toolchain. A binary archived with an Xcode beta
#   triggered an AppKit per-process image downscale in the shipped 2.1.2 beta 4
#   even though the source was correct (#572). `verify-artifact` enforces this.
# - The project uses automatic signing, so the app is built with default signing
#   and then deep re-signed inner->outer with the Developer ID identity.
# - Notarization uses the shared keychain profile; stapling requires full Xcode.
# - The appcast is generated by GitHub Pages from releases, and Pages only
#   rebuilds when explicitly triggered.
#
# Typical beta release, after the version-bump PR is merged and tagged:
#   just release-asset       # build, verify, sign, notarize, staple, zip
#   just smoke-test          # optional but recommended: live image-size check
#   just publish v2.1.2-beta-6 notes.md
#   just appcast

set shell := ["bash", "-cu"]

developer_dir := env_var_or_default("DEVELOPER_DIR", "/Applications/Xcode-27.0.0.app/Contents/Developer")
identity := "Developer ID Application: Ameba Labs, LLC (X93LWC49WV)"
notary_profile := "notarytool-kefir"
derived := "build-release"
app := derived / "Build/Products/Release/SwiftBar.app"
repo := "swiftbar/SwiftBar"

# List available recipes
default:
    @just --list

# Run the full test suite
test:
    DEVELOPER_DIR="{{developer_dir}}" xcodebuild test -project SwiftBar.xcodeproj -scheme SwiftBar -destination 'platform=macOS' -derivedDataPath "{{derived}}"

# Build the Release configuration (default signing; re-signed later by `sign`)
build:
    DEVELOPER_DIR="{{developer_dir}}" xcodebuild -project SwiftBar.xcodeproj -scheme SwiftBar -configuration Release -destination 'platform=macOS' -derivedDataPath "{{derived}}" build

# Verify the built artifact: released toolchain, helper name stamp
verify-artifact:
    @echo "Toolchain check..."
    @built=$(/usr/libexec/PlistBuddy -c "Print :DTXcodeBuild" "{{app}}/Contents/Info.plist"); \
    current=$(DEVELOPER_DIR="{{developer_dir}}" xcodebuild -version | awk '/Build version/ {print $3}'); \
    echo "  artifact DTXcodeBuild=$built, active xcodebuild=$current"; \
    if [ "$built" != "$current" ]; then echo "ERROR: artifact built with a different toolchain"; exit 1; fi; \
    case "$built" in *[A-Z][0-9]*[a-z]) ;; *) echo "ERROR: unexpected build id format: $built"; exit 1;; esac; \
    if printf '%s' "$built" | grep -qE '[0-9][A-Z]5[0-9]{3}[a-z]$'; then echo "ERROR: $built looks like a BETA Xcode build (27A5xxxx pattern) - use released Xcode"; exit 1; fi
    @echo "Helper stamp check..."
    @name=$(/usr/libexec/PlistBuddy -c "Print :CFBundleName" "{{app}}/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/Info.plist"); \
    echo "  helper CFBundleName=$name"; \
    if [ "$name" != "SwiftBar" ]; then echo "ERROR: helper CFBundleName is not SwiftBar - the Launch At Login build phase output is missing"; exit 1; fi
    @echo "verify-artifact OK"

# Deep re-sign inner->outer with the Developer ID identity
sign: verify-artifact
    @echo "Extracting production entitlements (stripping get-task-allow)..."
    codesign -d --entitlements - --xml "{{app}}" > "{{derived}}/app-entitlements.plist"
    plutil -remove "com.apple.security.get-task-allow" "{{derived}}/app-entitlements.plist" 2>/dev/null || true
    printf '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict><key>com.apple.security.app-sandbox</key><true/></dict></plist>\n' > "{{derived}}/helper-entitlements.plist"
    @echo "Signing Sparkle components..."
    for t in \
      "{{app}}/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate" \
      "{{app}}/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app" \
      "{{app}}/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc" \
      "{{app}}/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc" \
      "{{app}}/Contents/Frameworks/Sparkle.framework"; do \
        codesign --force --timestamp --options=runtime --sign "{{identity}}" "$t"; \
    done
    @echo "Signing login helper..."
    codesign --force --timestamp --options=runtime --entitlements "{{derived}}/helper-entitlements.plist" --sign "{{identity}}" "{{app}}/Contents/Library/LoginItems/LaunchAtLoginHelper.app"
    @echo "Sealing app..."
    codesign --force --timestamp --options=runtime --entitlements "{{derived}}/app-entitlements.plist" --sign "{{identity}}" "{{app}}"
    codesign --verify --deep --strict "{{app}}"
    @echo "sign OK"

# Zip the signed app using the appcast-parsed naming scheme
package:
    #!/usr/bin/env bash
    set -euo pipefail
    ver=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "{{app}}/Contents/Info.plist")
    build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "{{app}}/Contents/Info.plist")
    zip="SwiftBar.v${ver}.b${build}.zip"
    rm -f "$zip"
    ditto -c -k --keepParent "{{app}}" "$zip"
    echo "packaged $zip"

# Submit the packaged zip for notarization and wait
notarize:
    #!/usr/bin/env bash
    set -euo pipefail
    ver=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "{{app}}/Contents/Info.plist")
    build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "{{app}}/Contents/Info.plist")
    xcrun notarytool submit "SwiftBar.v${ver}.b${build}.zip" --keychain-profile "{{notary_profile}}" --wait

# Staple the notarization ticket and re-zip the final asset
staple:
    #!/usr/bin/env bash
    set -euo pipefail
    DEVELOPER_DIR="{{developer_dir}}" xcrun stapler staple "{{app}}"
    DEVELOPER_DIR="{{developer_dir}}" xcrun stapler validate "{{app}}"
    spctl -a -vv "{{app}}"
    ver=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "{{app}}/Contents/Info.plist")
    build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "{{app}}/Contents/Info.plist")
    zip="SwiftBar.v${ver}.b${build}.zip"
    rm -f "$zip"
    ditto -c -k --keepParent "{{app}}" "$zip"
    echo "final asset: $zip"

# Build, verify, sign, notarize, and staple in one go
release-asset: build sign package notarize staple

# Live check that menu bar images render at intrinsic size (needs GUI; catches b619-class artifact defects)
smoke-test:
    #!/usr/bin/env bash
    set -euo pipefail
    plugdir=$(mktemp -d)/plugins
    mkdir -p "$plugdir"
    b64=$(swift Scripts/release/make-smoke-icon.swift)
    printf '#!/bin/bash\necho "| image=%s"\necho "---"\necho "Smoke row"\n' "$b64" > "$plugdir/smoke.1h.sh"
    chmod +x "$plugdir/smoke.1h.sh"
    open "{{app}}" --args -PluginDirectory "$plugdir"
    sleep 6
    screencapture -x -R0,0,1470,30 Scripts/release/.smoke-bar.png
    result=$(swift Scripts/release/measure-smoke-icon.swift)
    pkill -f "{{app}}/Contents/MacOS/SwiftBar" || true
    rm -f Scripts/release/.smoke-bar.png Scripts/release/.smoke-icon.png
    echo "$result"
    if [ "$result" != "magenta block: 54 x 54 px" ]; then echo "ERROR: intrinsic image size not preserved"; exit 1; fi
    echo "smoke-test OK"

# Publish a prerelease with the packaged asset: just publish v2.1.2-beta-6 notes.md
publish tag notes:
    #!/usr/bin/env bash
    set -euo pipefail
    ver=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "{{app}}/Contents/Info.plist")
    build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "{{app}}/Contents/Info.plist")
    gh release create "{{tag}}" --repo {{repo}} --prerelease --title "$(echo "{{tag}}" | sed -E 's/^v//; s/-beta-/ BETA /')" --notes-file "{{notes}}" "SwiftBar.v${ver}.b${build}.zip"

# Trigger the GitHub Pages rebuild and wait for the beta appcast to update
appcast:
    #!/usr/bin/env bash
    set -euo pipefail
    build=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "{{app}}/Contents/Info.plist")
    gh api -X POST repos/{{repo}}/pages/builds --jq .status
    echo "waiting for appcast-beta.xml to serve b${build}..."
    for i in $(seq 1 40); do
        if curl -s https://swiftbar.github.io/SwiftBar/appcast-beta.xml | grep -q "b${build}.zip"; then
            echo "appcast OK: serving b${build}"
            exit 0
        fi
        sleep 15
    done
    echo "ERROR: appcast did not update within 10 minutes"
    exit 1
